<?php

return [
    'grades' => [
        'icon' => 'fa fa-book',
        'dashboard' => 'all',
        'title' => 'Grades',
        'route' => 'tenant/grades',
        'clickable' => true,
        'navbar' => true,
        'visibility' => false,
        'sub-menu' => [
            'grades' => [

                'dashboard' => 'all',
                'title' => 'All Grades',
                'route' => 'tenant/grades',
                'clickable' => true,
                'navbar' => true,
            ],
        ],
    ],
    'resources' => [
        'icon' => 'fa fa-file',
        'dashboard' => 'all',
        'title' => 'Resources',
        'route' => 'tenant/quiz',
        'clickable' => true,
        'navbar' => true,
        'visibility' => false,
        'sub-menu' => [
            'quiz' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'Quiz',
                'route' => 'tenant/quiz',
                'clickable' => true,
                'navbar' => true,
            ],
            'asset' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'Assets',
                'route' => 'tenant/assets',
                'clickable' => true,
                'navbar' => true,
            ],
        ],
    ],
    'course-mgt' => [
        'icon' => 'fa fa-graduation-cap',
        'dashboard' => 'all',
        'title' => 'Teaching Components',
        'route' => '#',
        'clickable' => true,
        'navbar' => true,
        'visibility' => false,
        'sub-menu' => [
            'modules' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'Modules',
                'route' => 'tenant/modules',
                'clickable' => true,
                'navbar' => true,
            ],
            'course' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'Courses',
                'route' => 'tenant/courses',
                'clickable' => true,
                'navbar' => true,
            ],
            'lesson' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'Tracks',
                'route' => 'tenant/lessons',
                'clickable' => true,
                'navbar' => true,
            ],
        ],
    ],
    'program-mgt' => [
        'icon' => 'fa fa-home',
        'dashboard' => 'all',
        'title' => 'Majors Management',
        'route' => '#',
        'clickable' => true,
        'navbar' => true,
        'visibility' => false,
        'sub-menu' => [
            'create' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'Create Major',
                'route' => 'tenant/programs/create',
                'clickable' => true,
                'navbar' => true,
            ],
            'programs' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'All Majors',
                'route' => 'tenant/programs',
                'clickable' => true,
                'navbar' => true,
            ],
        ],
    ],
    'courses' => [
        'icon' => 'fa fa-home',
        'dashboard' => 'all',
        'title' => 'Courses',
        'route' => 'learner/courses',
        'clickable' => true,
        'navbar' => true,
        'visibility' => false,
        'sub-menu' => [
            'my-courses' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'My Courses',
                'route' => 'learner/courses',
                'clickable' => true,
                'navbar' => true,
            ],
            'courses' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'Courses',
                'route' => 'learner/courses',
                'clickable' => true,
                'navbar' => true,
            ],
        ],
    ],
    'programs' => [
        'icon' => 'fa fa-home',
        'dashboard' => 'all',
        'title' => 'Programs',
        'route' => 'learner/programs',
        'clickable' => true,
        'navbar' => true,
        'visibility' => false,
        'sub-menu' => [
            'programs' => [
                'icon' => 'fa fa-home',
                'dashboard' => 'all',
                'title' => 'All Majors',
                'route' => 'learner/programs',
                'clickable' => true,
                'navbar' => true,
            ],
        ],
    ]
];
